# Generated by Django 3.1.3 on 2021-04-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='book',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
