# Generated by Django 3.1.3 on 2021-04-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='book',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
