# Generated by Django 3.1.3 on 2021-04-23 19:28

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210423_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='book',
            field=models.FileField(null=True, upload_to='uploads/', validators=[blog.validators.validate_file_extension]),
        ),
    ]
