# Generated by Django 3.1.3 on 2021-04-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210423_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='book_writer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
